### ISSUE TITLE
Getting warning

### ISSUE THREAD

**Issue by dlancea** [mifki/dfremote#2]
DFHack reports a warning after following the directions on http://mifki.com/df/setup/

Warning: Plugin remote compiled for DFHack 0.40.24-r5-0-g3330225, running DFHack v0.40.24-r5-0-g3330225

Kind of weird, thought I would report it.

**Comment by pronvit** [comment]
Yeah, I've seen it too with different plugins, never bothered to investigate because it doesn't actually affect anything.

**Comment by lethosor** [comment]
This specific one may be due to inconsistencies between `v0.40.24-r5` and `0.40.24-r5` (the `v`, specifically) in the tags for that release. That hasn't happened since then, so this probably isn't an issue any more.
