### ISSUE TITLE
Trade: incorrect value for instruments

### ISSUE THREAD

**Issue by BenLubar** [mifki/dfremote#4]
Example: https://benlubar.github.io/cmvjs/#https://ben.lubar.me/dump/ai_trade.cmv

(It might take a few seconds to start playing because the CMV file is being loaded from my home connection.)

The value generated for instruments is far below the value the game generates for them.

**Comment by pronvit** [comment]
Do you have a save, or can you share one next time you notice this or any wrong prices?

**Comment by BenLubar** [comment]
https://drive.google.com/file/d/0B5-zDODl1jqDQ0lFYkZHZnBxMDg/view?usp=sharing

I couldn't upload it to GitHub because as a zip it's more than 20MB. You can either `enable df-ai` and then interrupt it with `gui/gm-editor` or pull the save file out of there and throw it in your copy of Dwarf Fortress. The save should be pointing at the depot with traders ready with instruments.

**Comment by pronvit** [comment]
fixed.

**Comment by BenLubar** [comment]
Just for reference, this was fixed in d111850c8aaf85daed7a87a9cc5177150684131c.
